
modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="MIT license"
[[mods]] #mandatory
modId="crazyredstone"
version="0.0.1"
displayName="CrazyRedStone" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="crazyredstone.png" #optional
credits="hmm...." #optional
# A text field displayed in the mod UI
authors="Jrojro728" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
一个基于红石的科技mod
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.crazyredstone]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.crazyredstone]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
